# Generated by Django 3.2.9 on 2021-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20211104_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.CharField(max_length=50),
        ),
    ]
