# Generated by Django 3.2.9 on 2021-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_fixture_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
