# Generated by Django 3.2.9 on 2021-11-09 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20211108_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='home_team_goals',
            new_name='messi_ankles_team_goals',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='away_team_goals',
            new_name='opposing_team_goals',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='away_team',
            new_name='opposition_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_or_away',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
