# Generated by Django 3.2.9 on 2021-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20211109_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='home_or_away',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=1),
        ),
    ]
