# Generated by Django 3.2.9 on 2021-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_fixture_home_or_away'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='opposition_team',
            field=models.CharField(choices=[(2, 'Team Folded'), (3, 'Neptune FC'), (4, 'Pro Clubs'), (5, 'Back Post'), (6, 'Frauds FC'), (7, 'Eagles'), (8, 'Bears'), (9, 'Lions')], max_length=1),
        ),
    ]
