# Generated by Django 3.2.9 on 2021-11-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20211111_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
