# Generated by Django 3.2.9 on 2021-11-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_managers'),
        ('teams', '0013_auto_20211111_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='assist_maker',
        ),
        migrations.AddField(
            model_name='goal',
            name='assist_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist_maker', to='players.player'),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_scorer',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_scorer', to='players.player'),
        ),
    ]
