# Generated by Django 3.2.9 on 2021-11-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20211114_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalManager',
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
