# Generated by Django 3.2.9 on 2021-11-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20211114_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='messi_ankles_team_goals',
            new_name='away_team_goals',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='opposition_team_goals',
            new_name='home_team_goals',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_or_away',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='opposition_team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team'),
        ),
    ]
