# Generated by Django 3.2.9 on 2021-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20211114_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
    ]
