# Generated by Django 3.2.9 on 2021-11-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20211116_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_team_goals',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team_goals',
        ),
    ]
