# Generated by Django 3.2.9 on 2021-11-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_alter_fixture_away_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
