# Generated by Django 3.2.9 on 2021-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_remove_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='team', max_length=20),
            preserve_default=False,
        ),
    ]
