# Generated by Django 3.2.9 on 2021-11-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20211124_1827'),
        ('teams', '0025_auto_20211121_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='assist_maker',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_scorer',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_for',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
