# Generated by Django 3.2.9 on 2021-11-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211117_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
