# Generated by Django 3.2.8 on 2021-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fixtures',
            field=models.ManyToManyField(to='team_fixtures.Fixture'),
        ),
    ]
