# Generated by Django 3.2.8 on 2021-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixtures', '0002_team_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fixtures',
        ),
        migrations.AddField(
            model_name='fixture',
            name='teams',
            field=models.ManyToManyField(to='team_fixtures.Team'),
        ),
    ]
