# Generated by Django 3.2.8 on 2021-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fixtures', '0003_auto_20211029_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team_goals',
            field=models.IntegerField(blank=True),
        ),
    ]
