# Generated by Django 3.2.9 on 2021-11-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211117_2004'),
        ('teams', '0017_auto_20211116_1342'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.fixture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='ticket_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='number_of_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='order_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
