# Generated by Django 3.2.9 on 2021-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_ticket_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
