# Generated by Django 3.2.9 on 2021-11-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
        ('tickets', '0009_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.fixture'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.fixture'),
        ),
    ]
