# Generated by Django 3.2.8 on 2021-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image_url',
            new_name='close_up_image_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
