# Generated by Django 3.2.8 on 2021-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20211007_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
