# Generated by Django 3.2.8 on 2021-10-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='close_up_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
