# Generated by Django 3.2.8 on 2021-10-29 12:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20211027_1036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('players', django.db.models.manager.Manager()),
            ],
        ),
    ]
