# Generated by Django 3.2.8 on 2021-11-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
