# Generated by Django 3.2.9 on 2021-11-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='apearences',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
    ]
