# Generated by Django 3.2.9 on 2021-11-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20211119_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='apearences',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
    ]
