# Generated by Django 3.2.9 on 2021-11-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_auto_20211124_1827'),
        ('players', '0010_auto_20211124_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='teams.team'),
            preserve_default=False,
        ),
    ]
